#!/bin/sh
# (c) 2015, The MITRE Corporation. All rights reserved.
# Source code distributed pursuant to license agreement.
#
# Usage: bootstrap
# This script is designed to install all of the necessary dependencies for the
# services available.


# Make sure we are working with a 64-bit system.
ARCH=$(uname -m | sed 's/x86_//;s/amd//;s/i[3-6]86/32/')
echo "Architecture: $ARCH"

if [ $ARCH -ne '64' ]; then
  echo "** Non 64-bit system detected **"
  echo "These dependencies are for a 64-bit system."
  echo "Exiting.."
  exit
fi

# Determine the OS we are working with.
# Using lsb-release because os-release not available on Ubuntu 10.04
if [ -f /etc/lsb-release ]; then
  . /etc/lsb-release
  OS=$DISTRIB_ID
  VER=$DISTRIB_RELEASE
elif [ -f /etc/redhat-release ]; then
  OS=$(cat /etc/redhat-release | sed 's/ Enterprise.*//')
  VER=$(cat /etc/redhat-release | sed 's/.*release //;s/ .*$//')
else
  OS=$(uname -s)
  VER=$(uname -r)
fi

OS="$(echo "$OS" | tr "[:upper:]" "[:lower:]")"
VER="$(echo "$VER" | tr "[:upper:]" "[:lower:]")"

# Ubuntu: Install as many dependencies as we can using apt-get.
if [ "$OS" = 'ubuntu' ]
then
  echo "Installing dependencies with apt-get"
  sudo apt-add-repository universe
  sudo apt-get update
  sudo apt-get install -y --fix-missing libchm1 clamav upx wireshark
  sudo ldconfig

# Redhat: Install as many dependencies as we can using yum.
# TODO: Need to test centos dependencies
# elif [ "$OS" == 'centos' ] || [ "$OS" == 'redhat' ]
elif [ "$OS" = 'red hat' ]
then
  echo "Installing Yum Packages"
  # Probably should run the Yum equivelent of apt-get update
  sudo yum install upx-3.07-1 libchm1 clamav wireshark upx

# OSX: Install as many dependencies as we can using Homebrew.
elif [ "$OS" = 'darwin' ]
then
  command -v brew >/dev/null 2>&1 || {
    echo "Installation for OSX requires Homebrew. Please visit http://brew.sh/."
    exit
  }
  brew install chmlib clamav wireshark upx
elif [ "$OS" = 'freebsd' ]
then
  echo "Installing ports"
  sudo pkg install libchm1 clamav wireshark upx
else
  echo "Unknown distro!"
  echo "Detected: $OS $VER"
  exit
fi

# Install the rest of our dependencies which are python libraries.
echo "Installing Python Dependencies"
sudo pip install -r requirements.txt

echo "Dependency installations complete!"
echo "Please manually install the latest version of yara and yara-python."
